require 'lims-core/laboratory/plate/all'
require 'lims-core/laboratory/gel/all'
require 'lims-core/laboratory/tube/all'
require 'lims-core/laboratory/tube_rack/all'
require 'lims-core/laboratory/spin_column/all'
require 'lims-core/laboratory/flowcell/all'

require 'lims-core/laboratory/aliquot/all'
require 'lims-core/laboratory/sample/all'
require 'lims-core/laboratory/oligo/all'
require 'lims-core/laboratory/tag_group/all'
