require('lims-core/labels/labellable/create_labellable')
require('lims-core/labels/labellable/labellable_persistor')
require('lims-core/labels/labellable/labellable_sequel_persistor')
require('lims-core/labels/labellable')
require('lims-core/labels/sanger_barcode')
